name: ai_learn
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8y
  - matplotlib
  - graphviz
  - pip
  - pip:
    - matplotlib
    - tensorboard
    - scikit-learn
    - pandas
    - torchsummary
    - torchviz